### ISSUE TITLE
It would be great...

### ISSUE THREAD

**Issue by Zibri** [mausimus/ShaderGlass#16]
To have the following features:

1) integration or a better compatibility with VICE C64 emulator.
2) possibility to save the output as a screenshot and/or a video.

very good work so far!

**Comment by rohatsu** [comment]
Hey, thanks for the suggestions:
1. What particular issue are you encountering with VICE? It should work fine both in windowed and fullscreen modes, please provide more detail and I'd be happy to take a look.
2. Sure it's something quite straightforward, I will add a function to at least export a still image.
