### ISSUE TITLE
Scale input to locked ShaderGlass window size

### ISSUE THREAD

**Issue by ach80** [mausimus/ShaderGlass#24]
Please add options for Window/Clone mode, to lock ShaderGlass window to a precise, fixed size, so it scales input window (no matter its size) to that fixed output size.

**Comment by mausimus** [comment]
Hey, many thanks for the suggestion - I've included this in 0.7, please give it a shot.
https://github.com/mausimus/ShaderGlass/releases/download/v0.7/ShaderGlass-0.7-win-x64.zip
