### ISSUE TITLE
newpixie-crt renders wrong?

### ISSUE THREAD

**Issue by mabelmabelmabelmabel** [mausimus/ShaderGlass#25]
this is what it's showing me:
![image](https://user-images.githubusercontent.com/20459282/146615850-2bb57485-9c3e-421a-8d91-1d015bbb0054.png)
none of the settings seem to do anything about this. i'm not sure what other information would be helpful or if its just a me problem etc but it sucks because this is the prettiest filter ive found yet. btw, thanks for making this its the closest thing ive found to a usable crt monitor after weeks scouring thrift shops for a real one

**Comment by mausimus** [comment]
Hey, thanks for reporting this - fixed just in time for 0.7!
https://github.com/mausimus/ShaderGlass/releases/download/v0.7/ShaderGlass-0.7-win-x64.zip
