### ISSUE TITLE
Ability to "set default shader"

### ISSUE THREAD

**Issue by ferro4prez** [mausimus/ShaderGlass#30]
Hi! 

Super important FR: ability to "set default shader" when ShaderGlass opens.  We have all these abilities to customize shaders, but then every time we use ShaderGlass have to go through all the menus, find the shader, and load it.  Would be so simple to just pin a default shader that opens every time.

I envision creating the perfect shader, saving it as default, and whenever ShaderGlass opens it immediately is running it full-screen., and adding this to Windows Startup would be the icing on the cake.

**Comment by mausimus** [comment]
Hey, once you configure ShaderGlass you can save a profile file, and then launch it using a command line parameter; there's also a command-line option to start fullscreen. Please take a look at the docs.
