### ISSUE TITLE
Hall of mirrors bug

### ISSUE THREAD

**Issue by Tasosgemah** [mausimus/ShaderGlass#31]
This is how the CRT window looks for me:

![Untitled](https://user-images.githubusercontent.com/12124465/158031127-7031680c-784c-4bfe-a233-47611a5c39d6.png)

Is there a way to fix this?

**Comment by mausimus** [comment]
This is normal in Clone mode; go to Output -> Mode menu and try switching to Glass mode. If that doesn't work (frozen or black picture) then check your Windows version - you need 2004 (May 2020 update / build 19041) for Glass mode to work, but you can still use Clone mode (if you choose some source window in Input menu).

**Comment by Tasosgemah** [comment]
Ok, thanks. I had version 1909. Updating made glass mode work.
