### ISSUE TITLE
Low Text Quality

### ISSUE THREAD

**Issue by ToastyRetinas** [mausimus/ShaderGlass#39]
Hello! Almost everything I try has low quality text under Shaderglass? Is this a bug, a reality of small text on burner screens or fixable in settings.

Love this program, looking forward to bezels and CRT Royale, would love an ascii, monochrome (green beige et cetera) and the ability to stack shaders!

**Comment by mausimus** [comment]
By default ShaderGlass starts with 3x3 input pixel size; go to Input -> Pixel Size -> x1 to have pixel-to-pixel sharpness.
