### ISSUE TITLE
Hide Windows cursor in Capture Cursor mode.

### ISSUE THREAD

**Issue by MagnusPerotinus** [mausimus/ShaderGlass#42]
Capture Cursor - is it possible to hide the main Windows cursor in this mode somehow (just like DosBox does, for example)? Currently I have two cursors on the screen when I use ShaderGlass with this option enabled. You could bring back the cursor with some keys combination. Thank you and good luck.

**Comment by mausimus** [comment]
Hiding the cursor would require ShaderGlass to draw its own (like DOSBox does), a bigger feature to get this right. Tracked here: https://github.com/mausimus/ShaderGlass/issues/10
