### ISSUE TITLE
Minimizing to task bar resets shaders parameters.

### ISSUE THREAD

**Issue by ythoimust** [mausimus/ShaderGlass#43]
Minimizing ShaderGlass to task bar resets the shader parameters back to default. Easy to notice with for example lottes because I had those huge rings disabled and they come back every time. Reapeatable bug.

Id like to just say thanks, this software is amazing because it allows me to turn my lcd into kinda crt for work. For some type of graphics it is actually amazing.

Win 11

**Comment by mausimus** [comment]
fixed in 0.8
