### ISSUE TITLE
Fullscreen Issue with emulator

### ISSUE THREAD

**Issue by soulariax** [mausimus/ShaderGlass#52]
I've been using mGBA, I remember Shader Glass working a few months ago but now going into fullscreen in mGBA makes it lay over Shader Glass.

**Comment by smbhax** [comment]
I had a similar problem with the Apple II emulator "microm8"--not laying over ShaderGlass, but causing ShaderGlass to kind of vanish into a very small box with just a few menu options showing, if microm8 was full-screen.

Workaround has been keeping microm8 windowed but Maximized.
