### ISSUE TITLE
Please add video recording...

### ISSUE THREAD

**Issue by Zibri** [mausimus/ShaderGlass#53]
A great fature would be to add video recording and possibly in two ways:

1) normal, realtime.
2) no visualization, but record a window, apply shader and save video...

**Comment by QUAKEULUS** [comment]
I can't get any screen capture to work (nvidia geforce experience nor abs)
do i really need a second machine and capture card?

**Comment by mausimus** [comment]
Should work with OBS using Game Capture mode, see https://github.com/mausimus/ShaderGlass/blob/master/FAQ.md
